### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by egek92** [square/seismic#18]
In my application I have a feature like Google Maps' shake to feedback so I initialized the seismic inside my BaseActivity and extend every Activity from that. This causes leaks, is there another way to have shake detection in every activity I have?

**Comment by JakeWharton** [comment]
Are you calling stop()?

**Comment by egek92** [comment]
calling stop() in onStop

**Comment by JakeWharton** [comment]
How do you know it's leaking?

**Comment by egek92** [comment]
> calling stop() in onStop

turned out I wasn't calling it
